services:
  primary:
    build: primary
    container_name: pg_primary
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    shm_size: 1g
    cpus: 4
    mem_limit: 4g
    command: >
      postgres
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c listen_addresses='*'
      -c max_wal_size=4GB
      -c checkpoint_timeout=30min
      -c wal_keep_size=2GB
      -c shared_buffers=2GB
      -c work_mem=128MB
      -c maintenance_work_mem=512MB
      -c wal_buffers=32MB
      -c wal_level=replica
      -c max_wal_senders=10
      -c hot_standby=on
    ports:
      - "5432:5432"
    volumes:
      - primary_data:/var/lib/postgresql/data
      - .././datagen:/data/datagen
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - pgnet

  replica:
    build: replica
    container_name: pg_replica
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      PGPASSWORD: replica_pass
      PGDATA: /var/lib/postgresql/replica_data
      SHARED_BUFFERS: 2GB
      WORK_MEM: 128MB
      MAINTENANCE_WORK_MEM: 512MB
      WAL_BUFFERS: 32MB
      MAX_STANDBY_STREAMING_DELAY: 1000s
    depends_on:
      - primary
    shm_size: 1g
    cpus: 2
    mem_limit: 4g
    ports:
      - "5433:5432"
    volumes:
      - replica_data:/var/lib/postgresql/replica_data
    networks:
      - pgnet

volumes:
  primary_data:
  replica_data:

networks:
  pgnet:
