#!/bin/sh

# Print commands while executing
set -x

CLIENT_THREADS=2
KEYS=10
PARTITIONS=4
ZIPF_CONST=0.0
INPUT_MSG_PER_SEC=50
DURATION_SEC=60
SAVE_DIR=results
WARMUP_SEC=10
RUN_WITH_VALIDATION=True

python client.py \
	$CLIENT_THREADS \
	$KEYS \
	$PARTITIONS \
	$ZIPF_CONST \
	$INPUT_MSG_PER_SEC \
	$DURATION_SEC \
	$SAVE_DIR \
	$WARMUP_SEC \
	$RUN_WITH_VALIDATION
