analytical_queries = [
"""
SELECT SUM(lo.EXTENDEDPRICE*lo.DISCOUNT) AS REVENUE
FROM LINE_ORDER lo, DATE d
WHERE lo.ORDERDATE = d.DATEKEY
AND d.YEAR = 1993
AND lo.DISCOUNT BETWEEN 1 AND 3
AND lo.QUANTITY<25
""",
"""
SELECT SUM(lo.EXTENDEDPRICE*lo.DISCOUNT) AS REVENUE
FROM LINE_ORDER lo, DATE d
WHERE lo.ORDERDATE = d.DATEKEY
AND d.YEARMONTHNUM = 199401
AND lo.DISCOUNT BETWEEN 4 AND 6
AND lo.QUANTITY BETWEEN 26 AND 35
""",
"""
SELECT SUM(lo.EXTENDEDPRICE*lo.DISCOUNT) AS REVENUE
FROM LINE_ORDER lo, DATE d
WHERE lo.ORDERDATE = d.DATEKEY
AND d.WEEKNUMINYEAR = 6
AND d.YEAR = 1994
AND lo.DISCOUNT BETWEEN 5 AND 7
AND lo.QUANTITY BETWEEN 26 AND 35
""",
"""
SELECT SUM(lo.REVENUE), d.YEAR, p.BRAND1
FROM LINE_ORDER lo, DATE d, PART p, SUPPLIER s
WHERE lo.ORDERDATE = d.DATEKEY
AND lo.PARTKEY = p.PARTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND p.CATEGORY = 'MFGR#12'
AND s.REGION = 'AMERICA'
GROUP BY d.YEAR, p.BRAND1
ORDER BY d.YEAR, p.BRAND1
""",
"""
SELECT SUM(lo.REVENUE), d.YEAR, p.BRAND1
FROM LINE_ORDER lo, DATE d, PART p, SUPPLIER s
WHERE lo.ORDERDATE = d.DATEKEY
AND lo.PARTKEY = p.PARTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND p.BRAND1 BETWEEN 'MFGR#2221' AND 'MFGR#2228'
AND s.REGION = 'ASIA'
GROUP BY d.YEAR, p.BRAND1
ORDER BY d.YEAR, p.BRAND1
""",
"""
SELECT SUM(lo.REVENUE), d.YEAR, p.BRAND1
FROM LINE_ORDER lo, DATE d, PART p, SUPPLIER s
WHERE lo.ORDERDATE = d.DATEKEY
AND lo.PARTKEY = p.PARTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND p.BRAND1 = 'MFGR#2221'
AND s.REGION = 'EUROPE'
GROUP BY d.YEAR, p.BRAND1
ORDER BY d.YEAR, p.BRAND1
""",
"""
SELECT c.NATION, s.NATION, d.YEAR, SUM(lo.REVENUE) AS REVENUE
FROM CUSTOMER c, LINE_ORDER lo, SUPPLIER s, DATE d
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.ORDERDATE = d.DATEKEY
AND c.REGION = 'ASIA' AND s.REGION = 'ASIA'
AND d.YEAR >= 1992 AND d.YEAR <= 1997
GROUP BY c.NATION, s.NATION, d.YEAR
ORDER BY d.YEAR ASC, REVENUE DESC
""",
"""
SELECT c.CITY, s.CITY, d.YEAR, SUM(lo.REVENUE) AS REVENUE
FROM CUSTOMER c, LINE_ORDER lo, SUPPLIER s, DATE d
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.ORDERDATE = d.DATEKEY
AND c.NATION = 'UNITED STATES'
AND s.NATION = 'UNITED STATES'
AND d.YEAR >= 1992 AND d.YEAR <= 1997
GROUP BY c.CITY, s.CITY, d.YEAR
ORDER BY d.YEAR ASC, REVENUE DESC
""",
"""
SELECT c.CITY, s.CITY, d.YEAR, SUM(lo.REVENUE) AS REVENUE
FROM CUSTOMER c, LINE_ORDER lo, SUPPLIER s, DATE d
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.ORDERDATE = d.DATEKEY
AND (c.CITY = 'UNITED KI1' OR c.CITY = 'UNITED KI5')
AND (s.CITY = 'UNITED KI1' OR s.CITY = 'UNITED KI5')
AND d.YEAR >= 1992 AND d.YEAR <= 1997
GROUP BY c.CITY, s.CITY, d.YEAR
ORDER BY d.YEAR ASC, REVENUE DESC
""",
"""
SELECT c.CITY, s.CITY, d.YEAR, SUM(lo.REVENUE) AS REVENUE
FROM CUSTOMER c, LINE_ORDER lo, SUPPLIER s, DATE d
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.ORDERDATE = d.DATEKEY
AND (c.CITY = 'UNITED KI1' OR c.CITY = 'UNITED KI5')
AND (s.CITY = 'UNITED KI1' OR s.CITY = 'UNITED KI5')
AND d.YEARMONTH = 'Dec1994'
GROUP BY c.CITY, s.CITY, d.YEAR
ORDER BY d.YEAR ASC, REVENUE DESC
""",
"""
SELECT d.YEAR, c.NATION, SUM(lo.REVENUE-lo.SUPPLYCOST) AS PROFIT
FROM DATE d, CUSTOMER c, SUPPLIER s, PART p, LINE_ORDER lo
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.PARTKEY = p.PARTKEY
AND lo.ORDERDATE = d.DATEKEY
AND c.REGION = 'AMERICA'
AND s.REGION = 'AMERICA'
AND (p.MFGR = 'MFGR#1' OR p.MFGR = 'MFGR#2')
GROUP BY d.YEAR, c.NATION
ORDER BY d.YEAR, c.NATION
""",
"""
SELECT d.YEAR, c.NATION, p.CATEGORY, SUM(lo.REVENUE-lo.SUPPLYCOST) AS PROFIT
FROM DATE d, CUSTOMER c, SUPPLIER s, PART p, LINE_ORDER lo
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.PARTKEY = p.PARTKEY
AND lo.ORDERDATE = d.DATEKEY
AND c.REGION = 'AMERICA'
AND s.REGION = 'AMERICA'
AND (d.YEAR = 1997 OR d.YEAR = 1998)
AND (p.MFGR = 'MFGR#1' OR p.MFGR = 'MFGR#2')
GROUP BY d.YEAR, c.NATION, p.CATEGORY
ORDER BY d.YEAR, c.NATION, p.CATEGORY
""",
"""
SELECT d.YEAR, s.CITY, p.BRAND1, SUM(lo.REVENUE-lo.SUPPLYCOST) AS PROFIT
FROM DATE d, CUSTOMER c, SUPPLIER s, PART p, LINE_ORDER lo
WHERE lo.CUSTKEY = c.CUSTKEY
AND lo.SUPPKEY = s.SUPPKEY
AND lo.PARTKEY = p.PARTKEY
AND lo.ORDERDATE = d.DATEKEY
AND c.REGION = 'AMERICA'
AND s.NATION = 'UNITED STATES'
AND (d.YEAR = 1997 OR d.YEAR = 1998)
AND p.CATEGORY = 'MFGR#14'
GROUP BY d.YEAR, s.CITY, p.BRAND1
ORDER BY d.YEAR, s.CITY, p.BRAND1
"""
]